name: "Build and Deploy Site"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v19
        with:
          nix_conf: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v11
        with:
          name: antoinecarnecdotgithubdotio
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: nix build
        run: nix flake check && nix build -L --out-link ./out

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
